/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/nac/radius2.9/var/log/radius"
#define RADDBDIR	"/nac/radius2.9/etc/raddb"
#define RUNDIR		"/nac/radius2.9/var/run"
#define SBINDIR		"/nac/radius2.9/sbin"
#define RADIR		"/nac/radius2.9/var/log/radius/radacct"
